"""Bot templates — pre-built recipes for common use cases."""

TEMPLATES = [
    {
        "id": "web-scout",
        "name": "Web-Scout",
        "emoji": "🔍",
        "description": "Sucht regelmäßig im Internet nach einem Thema und meldet Neuigkeiten",
        "prompt": "Suche im Internet nach den neuesten Nachrichten und Entwicklungen zu [DEIN THEMA]. Fasse die 3 wichtigsten Ergebnisse zusammen mit Titel, Quelle und einer kurzen Beschreibung. Vergleiche mit deinem letzten Ergebnis und hebe hervor was NEU ist.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": "0 * * * *",
        "category": "Recherche",
    },
    {
        "id": "summarizer",
        "name": "Zusammenfasser",
        "emoji": "📝",
        "description": "Fasst lange Texte in klare Bullet-Points zusammen",
        "prompt": "Fasse den folgenden Text in maximal 5 klaren Bullet-Points zusammen. Fokussiere auf die wichtigsten Aussagen und Fakten. Schreibe auf Deutsch.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Text",
    },
    {
        "id": "translator",
        "name": "Übersetzer",
        "emoji": "🌍",
        "description": "Übersetzt Texte professionell zwischen Sprachen",
        "prompt": "Übersetze den folgenden Text ins [ZIELSPRACHE]. Achte auf natürlichen Sprachfluss und kulturelle Anpassung. Gib nur die Übersetzung aus, keine Erklärungen.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Text",
    },
    {
        "id": "email-responder",
        "name": "Mail-Antwort",
        "emoji": "📧",
        "description": "Schreibt professionelle Antworten auf E-Mails",
        "prompt": "Schreibe eine professionelle, freundliche Antwort auf die folgende E-Mail. Halte den Ton geschäftlich aber warm. Beantworte alle Fragen und schlage nächste Schritte vor. Formatiere als fertige E-Mail mit Betreff.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Kommunikation",
    },
    {
        "id": "researcher",
        "name": "Recherche-Bot",
        "emoji": "🧪",
        "description": "Recherchiert ein Thema gründlich und erstellt einen Bericht",
        "prompt": "Recherchiere gründlich zum Thema [DEIN THEMA]. Erstelle einen strukturierten Bericht mit: 1) Zusammenfassung, 2) Wichtigste Fakten, 3) Aktuelle Entwicklungen, 4) Quellen. Nutze die Web-Suche für aktuelle Informationen.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": None,
        "category": "Recherche",
    },
    {
        "id": "price-tracker",
        "name": "Preis-Tracker",
        "emoji": "💰",
        "description": "Überwacht Preise und meldet Schnäppchen",
        "prompt": "Suche im Internet nach [PRODUKT] und finde die besten aktuellen Angebote unter [MAX-PREIS]€. Liste für jeden Treffer: Produkt, Preis, Shop, Link. Vergleiche mit deinem letzten Ergebnis und markiere neue Angebote mit 🆕.",
        "model": "gpt-4o-mini",
        "tools": ["web_search", "files"],
        "schedule": "0 */2 * * *",
        "category": "Shopping",
    },
    {
        "id": "daily-briefing",
        "name": "Tages-Briefing",
        "emoji": "☀️",
        "description": "Erstellt jeden Morgen eine Zusammenfassung der wichtigsten Nachrichten",
        "prompt": "Erstelle ein kurzes Morgen-Briefing mit den 5 wichtigsten Nachrichten des Tages aus Deutschland und der Welt. Pro Nachricht: Emoji, Überschrift, 1-2 Sätze. Am Ende: Wetter-Trend falls verfügbar.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": "0 7 * * *",
        "category": "News",
    },
    {
        "id": "code-reviewer",
        "name": "Code-Reviewer",
        "emoji": "💻",
        "description": "Prüft Code auf Fehler, Sicherheitslücken und Verbesserungsmöglichkeiten",
        "prompt": "Prüfe den folgenden Code auf: 1) Bugs und Fehler, 2) Sicherheitslücken, 3) Performance-Probleme, 4) Code-Qualität. Gib konkrete Verbesserungsvorschläge mit Code-Beispielen.",
        "model": "claude-sonnet-4-20250514",
        "tools": ["files"],
        "schedule": None,
        "category": "Entwicklung",
    },
]
