"""Bot templates — pre-built recipes for common use cases."""

TEMPLATES = [
    {
        "id": "web-scout",
        "name": "Web Scout",
        "emoji": "",
        "icon": "search",
        "description": "Regularly searches the web for a topic and reports changes",
        "prompt": "Search the internet for the latest news and developments on [YOUR TOPIC]. Summarize the 3 most important results with title, source and brief description. Compare with your last result and highlight what's NEW.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": "0 * * * *",
        "category": "Research",
    },
    {
        "id": "summarizer",
        "name": "Summarizer",
        "emoji": "",
        "icon": "file-text",
        "description": "Condenses long texts into clear bullet points",
        "prompt": "Summarize the following text in a maximum of 5 clear bullet points. Focus on the most important statements and facts.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Text",
    },
    {
        "id": "translator",
        "name": "Translator",
        "emoji": "",
        "icon": "languages",
        "description": "Professionally translates texts between languages",
        "prompt": "Translate the following text to [TARGET LANGUAGE]. Ensure natural flow and cultural adaptation. Output only the translation, no explanations.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Text",
    },
    {
        "id": "email-responder",
        "name": "Email Responder",
        "emoji": "",
        "icon": "mail",
        "description": "Writes professional replies to emails",
        "prompt": "Write a professional, friendly response to the following email. Keep the tone business-appropriate but warm. Answer all questions and suggest next steps. Format as a ready-to-send email with subject line.",
        "model": "gpt-4o-mini",
        "tools": [],
        "schedule": None,
        "category": "Communication",
    },
    {
        "id": "researcher",
        "name": "Deep Researcher",
        "emoji": "",
        "icon": "microscope",
        "description": "Thoroughly researches a topic and creates a structured report",
        "prompt": "Thoroughly research the topic [YOUR TOPIC]. Create a structured report with: 1) Summary, 2) Key facts, 3) Current developments, 4) Sources. Use web search for current information.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": None,
        "category": "Research",
    },
    {
        "id": "price-tracker",
        "name": "Price Tracker",
        "emoji": "",
        "icon": "trending-down",
        "description": "Monitors prices and reports deals",
        "prompt": "Search the internet for [PRODUCT] and find the best current offers under $[MAX_PRICE]. List for each result: Product, Price, Shop, Link. Compare with your last result and mark new offers.",
        "model": "gpt-4o-mini",
        "tools": ["web_search", "files"],
        "schedule": "0 */2 * * *",
        "category": "Shopping",
    },
    {
        "id": "daily-briefing",
        "name": "Daily Briefing",
        "emoji": "",
        "icon": "newspaper",
        "description": "Creates a morning summary of the most important news",
        "prompt": "Create a concise morning briefing with the 5 most important news items of the day. Per item: headline, 1-2 sentences. Include a mix of world news, tech, and business.",
        "model": "gpt-4o-mini",
        "tools": ["web_search"],
        "schedule": "0 7 * * *",
        "category": "News",
    },
    {
        "id": "code-reviewer",
        "name": "Code Reviewer",
        "emoji": "",
        "icon": "code",
        "description": "Reviews code for bugs, security issues and improvements",
        "prompt": "Review the following code for: 1) Bugs and errors, 2) Security vulnerabilities, 3) Performance issues, 4) Code quality. Provide concrete improvement suggestions with code examples.",
        "model": "claude-sonnet-4-20250514",
        "tools": ["files"],
        "schedule": None,
        "category": "Development",
    },
    {
        "id": "system-monitor",
        "name": "System Monitor",
        "emoji": "",
        "icon": "server",
        "description": "Checks system health, updates, and resource usage",
        "prompt": "Check the system for: 1) Available package updates, 2) Disk usage, 3) Memory usage, 4) Running services status. Report any issues or items needing attention.",
        "model": "gpt-4o-mini",
        "tools": ["code"],
        "schedule": "0 9 * * *",
        "category": "DevOps",
    },
]
